### PR TITLE
Omitting some extra unnecessary lines of code

### PR DESCRIPTION
**Pull request by samytto**
Hi,

Cleaning out some unnecessary lines of code, supposedly forgotten during code modification ;-)

### CODE REVIEW

**Comment by lemire** [comment]
Thanks. Had to merge manually : 

https://github.com/lemire/sparsebitmap/commit/897987beae5ea8e4745ad2295632ca8bb174b944

**Comment by samytto** [comment]
I can see that you have encontered and fixed the same problem in the xor2by2 method, but my pull request was fixing the or2by2 method.

**Comment by lemire** [comment]
Indeed. Fixed:

https://github.com/lemire/sparsebitmap/commit/d4a107874c2712c3b2dd5f5e0e8868bfb524ba82

**Comment by samytto** [comment]
Great!

**Pull request closed without merging**
